version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: buyebye
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - buyebye-ecommerce

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - buyebye-ecommerce

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - buyebye-ecommerce

  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    networks:
      - buyebye-ecommerce

  # discount-api:
  #   build: 
  #     context: ../discount/
  #     dockerfile: dockerfile
  #   container_name: discount-api
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - kafka
  #     - postgres
  #   environment:
  #     POSTGRES_DB_HOST: postgres
  #     POSTGRES_DB_PASSWORD: 123
  #     POSTGRES_DB_USER: adm
  #     KAFKA_HOST: kafka
  #   networks:
  #     - buyebye-ecommerce

  # products-api:
  #   build: 
  #     context: ../products/
  #     dockerfile: dockerfile
  #   container_name: products-api
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - kafka
  #     - postgres
  #     - discount-api
  #   environment:
  #     POSTGRES_DB_HOST: postgres
  #     POSTGRES_DB_PASSWORD: 123
  #     POSTGRES_DB_USER: adm
  #     KAFKA_HOST: kafka
  #   networks:
  #     - buyebye-ecommerce

networks:
  buyebye-ecommerce:
    driver: bridge

volumes:
  postgres_data:
